---
# tasks file for elastic-search

- name: Install Wget
  apt:
    name: wget
    state: present

- name: Install elastic search repo
  ignore_errors: True
  shell: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"
  
- name: Install transport https pkg
  apt:
    name: apt-transport-https
    state: present

- name: Save Repository definitions
  shell: echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list

- name: update cache and ignore errors in case of problems
  apt: update_cache=yes
  ignore_errors: yes

- name: Install elastic search
  apt:
    name: elasticsearch
    state: present
  notify: 
  - restart-elastic-search

- name: copy-elastic-search-conf-file
  template:
    src: templates/elasticsearch-master.yaml
    dest:  /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: 
  - restart-elastic-search  





    




  